---
- name: Deploy Kubernetes Resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Apply Kubernetes manifests
      ansible.builtin.shell:
        cmd: kubectl apply -f ./k8s-manifests/
