version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    restart: always
    networks:
      - spe-network
    environment:
      MYSQL_DATABASE: ticketresolver
      MYSQL_ROOT_PASSWORD: Abcd@1234
      MYSQL_PASSWORD: Abcd@1234
      MYSQL_USER: spe-project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  ticketresolver_backend:
    image: madhavsood04/ticketresolver-backend:latest
    container_name: ticketresolver_backend
    restart: always
    networks:
      - spe-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/ticketresolver?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: spe-project
      SPRING_DATASOURCE_PASSWORD: Abcd@1234
    ports:
      - "8081:8081"
    depends_on:
      - mysql_db

  ticketresolver_frontend:
    image: madhavsood04/ticketresolver_frontend:latest
    container_name: ticketresolver_frontend
    restart: always
    networks:
      - spe-network
    ports:
      - "3000:3000"
    depends_on:
      - ticketresolver_backend

networks:
  spe-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local