---
- name: Pull backend image
  docker_image:
    name: madhavsood04/ticketresolver-backend:latest
    source: pull

- name: Pull frontend image
  docker_image:
    name: madhavsood04/ticketresolver_frontend:latest
    source: pull

- name: Pull mysql image
  docker_image:
    name: mysql
    source: pull