apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ticketresolver-backend
  name: ticketresolver-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticketresolver-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ticketresolver-backend
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: Abcd@1234
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql_db:3306/ticketresolver?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: spe-project
          image: madhavsood04/ticketresolver-backend:latest
          name: ticketresolver-backend
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: logs-volume
      restartPolicy: Always
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-volume
